<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{628c5be1-be64-4f4a-b2c2-f4ac993c6eab}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bInput : BOOL;
	bOutput : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[bOutput := bInput;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>